name: flutter_structure
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  provider: ^6.0.1
  uuid: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_native_splash: ^2.1.2+1
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  formz: ^0.4.0
  built_collection: ^5.0.0
  built_value: ^8.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/ic_instagram.svg
 
